### ISSUE TITLE
Date of release in repos?

### ISSUE THREAD

**Issue by glockbender** [springfox/springfox-javadoc#3]
Hi. Could you answer please, when should we expect the release of the plug-in in the repository? Thanks for your answer.

**Comment by dilipkrish** [comment]
It has been released to jcenter. Not to maven central

**Comment by dilipkrish** [comment]
Will release it shortly to maven central as well ... the version is `0.9.3`

**Comment by neumaennl** [comment]
I saw that 0.9.4 is in maven central. Can this bug be closed?

**Comment by dilipkrish** [comment]
Yes it can be. Thanks for pointing that out
